<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.8.9"/>
<title>ZWSoft ZRX for ZWCAD: Developer Guide: Object Snap</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectlogo"><img alt="Logo" src="logo.png"/></td>
  <td style="padding-left: 0.5em;">
   <div id="projectname">ZWSoft ZRX for ZWCAD: Developer Guide
   &#160;<span id="projectnumber">2022</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.9 -->
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">Object Snap<div class="ingroups"><a class="el" href="group___basic_interaction.html">Basic Interaction with ZWCAD</a> &raquo; <a class="el" href="group___global_func.html">Global Functions for Interacting with ZWCAD</a> &raquo; <a class="el" href="group___g_f_general.html">General Access</a></div></div>  </div>
</div><!--header-->
<div class="contents">
<p>Use the acedOsnap () function to specify a snap pattern to capture a point</p>
<p><br />
 The following code uses the acedOsnap () function to capture a circle's center. <br />
 The result is the circle's center(10.000000,10.000000,0.000000) </p><div class="fragment"><div class="line"><span class="keywordtype">void</span> InteractGlobalFunction::ObjectSnap()</div>
<div class="line">{</div>
<div class="line">    ads_point ptCenter = {10, 10, 0}; </div>
<div class="line">    ads_real radius = 10.0;  </div>
<div class="line">    acedCommand(RTSTR, _T(<span class="stringliteral">&quot;circle&quot;</span>),</div>
<div class="line">        RT3DPOINT, ptCenter,</div>
<div class="line">        RTREAL, radius, </div>
<div class="line">        RTNONE);</div>
<div class="line"></div>
<div class="line">    ads_point pt1={0, 10, 0};<span class="comment">//A point on the circle</span></div>
<div class="line">    ads_point pt2;</div>
<div class="line">    acedOsnap(pt1,_T(<span class="stringliteral">&quot;center&quot;</span>),pt2);</div>
<div class="line">    </div>
<div class="line">    acutPrintf(_T(<span class="stringliteral">&quot;%f,%f,%f&quot;</span>),pt2[0],pt2[1],pt2[2]);</div>
<div class="line">}</div>
</div><!-- fragment --> </div><!-- contents -->
<hr class="footer"/><address class="footer"><small>
<a href="https://www.zwsoft.com/zwcad/Developers/">
<img class="footer" src="zwsoft.png" alt="zwsoft"/></br>
</a>
&copy; 1998-2022  Copyright ZWSOFT CO., LTD(Guangzhou)</br>
All rights reserved.
</small></address>
</body>
</html>
